import { createServiceClient } from "@/lib/supabase/server";
import { updateGeneralSettings } from "./actions";
import { ArrowLeft, Save, FileText, Settings2 } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

export const metadata = { title: "General Settings" };

export default async function GeneralSettingsPage() {
  const supabase = createServiceClient();
  const { data: settings } = await supabase.from("app_settings").select("*").single();

  if (!settings) {
    redirect("/settings");
  }

  return (
    <div className="space-y-6 animate-fade-in max-w-2xl">
      <div className="flex items-center gap-4">
        <Link 
          href="/settings"
          className="p-2 -ml-2 rounded-lg hover:bg-zinc-800 text-zinc-400 hover:text-zinc-100 transition-colors"
        >
          <ArrowLeft size={20} />
        </Link>
        <div>
          <h2 className="text-lg font-bold text-zinc-100">General Settings</h2>
          <p className="text-sm text-zinc-500">Manage company branding and system names</p>
        </div>
      </div>

      <div className="p-5 rounded-xl bg-zinc-900 border border-zinc-800">
        <form action={updateGeneralSettings} className="space-y-6">
          <div className="space-y-4">
            <div>
              <label className="flex items-center gap-2 text-sm font-medium text-zinc-200 mb-1.5">
                <FileText size={16} className="text-indigo-400" />
                Company / Business Name
              </label>
              <p className="text-xs text-zinc-500 mb-3">
                This name will appear on all exported PDF reports and invoices.
              </p>
              <input
                type="text"
                name="companyName"
                defaultValue={settings.company_name || "MiBx"}
                placeholder="e.g. MiBx Fashion"
                className="w-full bg-black border border-zinc-700 rounded-md px-3 py-2 text-sm text-zinc-200 outline-none focus:border-indigo-500"
                required
              />
            </div>

            <div className="h-px w-full bg-zinc-800" />

            <div>
              <label className="flex items-center gap-2 text-sm font-medium text-zinc-200 mb-1.5">
                <Settings2 size={16} className="text-indigo-400" />
                Dispatch System Name
              </label>
              <p className="text-xs text-zinc-500 mb-3">
                This will be shown in the footer of your generated reports (e.g., "Generated by MiBx Dispatch").
              </p>
              <input
                type="text"
                name="systemName"
                defaultValue={settings.system_name || "MiBx Dispatch"}
                placeholder="e.g. MiBx Dispatch"
                className="w-full bg-black border border-zinc-700 rounded-md px-3 py-2 text-sm text-zinc-200 outline-none focus:border-indigo-500"
                required
              />
            </div>
          </div>

          <div className="flex justify-end pt-2">
            <button
              type="submit"
              className="bg-indigo-500 hover:bg-indigo-600 text-white px-5 py-2 rounded-md text-sm font-medium transition-colors flex items-center gap-2"
            >
              <Save size={16} />
              Save Settings
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
